// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPICourse.Data;

#nullable disable

namespace WebAPICourse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804202032_AddCategoryAndProductRelationship")]
    partial class AddCategoryAndProductRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPICourse.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Input devices such as mice and keyboards",
                            Name = "Peripherals"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Add-ons and connectivity accessories",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Devices for storing and transferring data",
                            Name = "Storage"
                        });
                });

            modelBuilder.Entity("WebAPICourse.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 24.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "RGB backlit mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "7-in-1 USB-C hub",
                            Name = "USB-C Hub",
                            Price = 39.99m,
                            StockQuantity = 200
                        });
                });

            modelBuilder.Entity("WebAPICourse.Models.Product", b =>
                {
                    b.HasOne("WebAPICourse.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebAPICourse.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
